spring.application.name=LmsPortalApplication

sserver.port=8080


spring.datasource.url=jdbc:mysql://localhost:3306/lms_portal1
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


jwt.secret=
jwt.expiration=86400000


# allow swagger in security config
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true


spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

gemini.api.key=
stripe.secretKey=

server.servlet.session.timeout=30m
